apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: devops-project
          image: soham1810/test-image:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: devops-app-secret
                  key: APP_ENV
            - name: APP_PORT
              valueFrom:
                secretKeyRef:
                  name: devops-app-secret
                  key: APP_PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: devops-app-config
                  key: LOG_LEVEL
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: devops-app-config
                  key: APP_NAME
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  name: devops-app-config
                  key: VERSION
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_PASSWORD
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
